### PR TITLE
Add 'mini' style to Records list and add it to Nighmare Hunts triumphs; Add Letters from Eris lore triumph entries to Nightmare Hunt triumphs

### PR DESCRIPTION
**Pull request by FlaminSarge**

### CODE REVIEW

**Comment by justrealmilk** [comment]
this would make
192 168 1 117_3000_1_4611686018449662397_2305843009260574394_this-week (9)

**Comment by FlaminSarge** [comment]
Yeah, which is why I was experimenting with a smaller indicator for time trial and lore badges. The other option is to make it a 2-column module. Thoughts?

**Comment by FlaminSarge** [comment]
Working on a 'mini' style for Records that should alleviate the length, plan is to show just the triumph title/icon as a small bar and link to the actual triumph page (as Records currently do) for the full details. No description, potentially no tooltip, smaller icon, etc. Marking this as WIP.

**Comment by FlaminSarge** [comment]
image

**Pull request closed without merging**
